# Generated by Django 4.2.19 on 2025-04-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('fecha_declaracion', models.DateField()),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('familia_linguistica', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_permiso', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('disponibilidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Batalla',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mi_app.historia')),
                ('lugar', models.CharField(max_length=255)),
                ('resultado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mi_app.historia')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mi_app.evento')),
                ('tema', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCultural',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mi_app.evento')),
                ('representacion_tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventoDeportivo',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mi_app.evento')),
                ('tipo_deporte', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventoGastronomico',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mi_app.evento')),
                ('tipo_comida', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Independencia',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mi_app.historia')),
                ('fecha_declaracion', models.DateField()),
                ('pais', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mi_app.historia')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True)),
                ('contribucion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(default='temporal_contrasena', max_length=255)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_recuperacion', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('id_rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_app.rol')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_archivo', models.CharField(max_length=2048)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.CharField(max_length=255)),
                ('detalle', models.TextField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('anio_publicacion', models.DateField()),
                ('enlace', models.CharField(max_length=2048)),
                ('descripcion', models.TextField()),
                ('id_historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.historia')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.evento')),
            ],
        ),
        migrations.CreateModel(
            name='CostumbresEtnias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=255)),
                ('id_etnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.etnia')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.historia')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.rol')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Presidente',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mi_app.personaje')),
                ('periodo_gobierno', models.CharField(max_length=255)),
                ('partido_politico', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.permisos')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.rol')),
            ],
            options={
                'unique_together': {('id_permiso', 'id_rol')},
            },
        ),
        migrations.CreateModel(
            name='Organiza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.evento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.usuario')),
            ],
            options={
                'unique_together': {('id_usuario', 'id_evento')},
            },
        ),
        migrations.CreateModel(
            name='MultimediaH',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mi_app.multimedia')),
                ('id_historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.historia')),
            ],
        ),
        migrations.CreateModel(
            name='MultimediaE',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mi_app.multimedia')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.evento')),
            ],
        ),
        migrations.CreateModel(
            name='IdiomasEtnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_uso', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('id_etnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.etnia')),
                ('id_idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.idioma')),
            ],
            options={
                'unique_together': {('id_etnia', 'id_idioma')},
            },
        ),
        migrations.CreateModel(
            name='EventoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.IntegerField()),
                ('observaciones', models.TextField()),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.evento')),
                ('id_recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.recursos')),
            ],
            options={
                'unique_together': {('id_evento', 'id_recurso')},
            },
        ),
        migrations.CreateModel(
            name='EventoPatrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_apoyo', models.CharField(max_length=255)),
                ('monto_aportado', models.IntegerField()),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.evento')),
                ('id_patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.patrocinadores')),
            ],
            options={
                'unique_together': {('id_evento', 'id_patrocinador')},
            },
        ),
        migrations.CreateModel(
            name='EventoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.evento')),
                ('id_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.participantes')),
            ],
            options={
                'unique_together': {('id_evento', 'id_participante')},
            },
        ),
        migrations.AddField(
            model_name='etnia',
            name='id_cultura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.cultura'),
        ),
        migrations.CreateModel(
            name='Esta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.agenda')),
                ('id_cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.cronograma')),
            ],
            options={
                'unique_together': {('id_cronograma', 'id_agenda')},
            },
        ),
        migrations.CreateModel(
            name='ParticipaI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_independencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.independencia')),
                ('id_personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.personaje')),
            ],
            options={
                'unique_together': {('id_independencia', 'id_personaje')},
            },
        ),
        migrations.CreateModel(
            name='ParticipaB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_batalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.batalla')),
                ('id_personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.personaje')),
            ],
            options={
                'unique_together': {('id_personaje', 'id_batalla')},
            },
        ),
    ]
