# Generated by Django 4.2.19 on 2025-05-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('id_cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.cronograma')),
            ],
        ),
    ]
