# Generated by Django 4.2.19 on 2025-03-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_recuperacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
